### ISSUE TITLE
readme?

### ISSUE THREAD

**Issue by ghost** [manyouit/PasteAsHardlink#1]
Can you please include a readme about the proper way to use this and how this script works? (junctionpoint / hardlink functionality does not need to be explained)

**Comment by Chigogo** [comment]
OK。Just install AHK and use AHK to run my .ahk file.

**Comment by manyouit** [comment]
https://github.com/manyouit/PasteAsHardlink/commit/5066fc7830ed4237e255d748336110515e9f86c7

We have a readme file. Check that and go to https://github.com/manyouit/PasteAsHardlink to view it.
